[pytest]
python_files = test_*.py
python_classes = Test*
python_functions = test_*


markers =
    ui: Запускает все UI автотесты
    smoke: Запускает смоук тесты
    regression: Запускает регрессионные
    slow: Запускает медленные тесты
    registration: запуск для регистрации
    authorization: авторизация